# Script para eliminar todos los archivos relacionados a proveedores de libros
del /f /q "controllers\proveedoresLibroController.js"
del /f /q "models\ProveedorLibro.js"
del /f /q "routes\proveedores_libros.js"
del /f /q "routes\api\proveedores_libros.js"
del /f /q "migrar_proveedores_a_libros.js"
del /f /q "migrar_proveedores_libros_a_proveedores.js"
del /f /q "borrar_coleccion_proveedorlibros.js"
del /f /q "views\proveedor_libro\catalogo_proveedores_libro.pug"
del /f /q "views\proveedor_libro\editar_proveedor_libro.pug"
del /f /q "views\proveedor_libro\nuevo_proveedor_libro.pug"
del /f /q "public\js\proveedor_libro\catalogo_proveedores_libro.js"
del /f /q "public\js\proveedor_libro\editar_proveedor_libro.js"
del /f /q "public\js\proveedor_libro\nuevo_proveedor_libro.js"
